---
provisioner:
  name: chef_solo
  environments_path: environments
  data_bags_path: "test/integration/data_bags"
  encrypted_data_bag_secret_key_path: "encrypted_data_bag_secret"

suites:
  - name: default
    provisioner:
      solo_rb:
        environment: vagrant
    run_list:
      - recipe[ganeti_webmgr::default]
      - recipe[ganeti_webmgr::bootstrap_user]
      - recipe[ganeti_webmgr::apache]
      - recipe[ganeti_webmgr::haystack]
    attributes:
      ganeti_webmgr:
        database:
          engine: 'django.db.backends.sqlite3'

  - name: mysql
    provisioner:
      solo_rb:
        environment: vagrant
    run_list:
      - recipe[gwm_test]
      - recipe[ganeti_webmgr::default]
      - recipe[ganeti_webmgr::bootstrap_user]
      - recipe[ganeti_webmgr::apache]
      - recipe[ganeti_webmgr::haystack]
