---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "33.33.33.110", adapter: 2}]

provisioner:
  name: chef_solo
  environments_path: environments
  data_bags_path: "test/integration/data_bags"
  encrypted_data_bag_secret_key_path: "encrypted_data_bag_secret"

platforms:
  - name: centos-6.5
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[ganeti_webmgr::default]
      - recipe[ganeti_webmgr::bootstrap_user]
      - recipe[ganeti_webmgr::apache]
    attributes:
      ganeti_webmgr:
        database:
          engine: django.db.backends.sqlite3
          name: /home/vagrant/gwm.db
        vncauthproxy:
          port: "8888"

  - name: mysql
    run_list:
      - recipe[ganeti_webmgr::mysql]
      - recipe[ganeti_webmgr::bootstrap_user]
      - recipe[ganeti_webmgr::apache]
