---
provisioner:
  name: chef_solo
  data_bags_path: "test/integration/data_bags"
  encrypted_data_bag_secret_key_path: "encrypted_data_bag_secret"
  attributes:
    ganeti_webmgr:
      revision: master
      debug: true
      migrate: true
      database:
        name: ganeti_webmgr
        user: ganeti_webmgr
        password: ganeti_webmgr
        host: localhost
      apache:
        server_aliases:
          - localhost

suites:
  - name: default
    run_list:
      - recipe[ganeti_webmgr::default]
    attributes:
      ganeti_webmgr:
        database:
          engine: 'django.db.backends.sqlite3'
          name: /opt/ganeti_webmgr/ganeti_webmgr

  - name: mysql
    run_list:
      - recipe[gwm_test]
      - recipe[ganeti_webmgr::default]
