name             'gwm_test'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache-2.0'
description      'Installs/Configures gwm_test'
version          '0.1.0'
depends          'certificate'
depends          'database'
depends          'ganeti_webmgr'
depends          'mariadb'
